begonia: props: Fix a duplicate
* It is now project-wide by riceDroid so it causes build to fail:
error: found duplicate sysprop assignments:
pm.dexopt.install=speed-profile
pm.dexopt.install=speed

Signed-off-by: MrErenK <akbaseren4751@gmail.com>